#! /usr/bin/env python
# -*- coding: iso-8859-1 -*-
"""Short description.

Full description.
"""

__author__ = "__user_name__ <__user_email__>"
__date__ = "__creation_date__"
__version__ = "$Id$"
__credits__ = """Copyright (C) 2003 __user_name__.

This is free software; you can redistribute it and/or modify it under the terms
of the GNU General Public License as published by the Free Software Foundation;
either version 2 of the License, or (at your option) any later version.

This is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.
"""

